services:
  - type: web
    name: abonnement-stripe
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
